name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  lint:
    uses: yetanalytics/workflow-linter/.github/workflows/linter.yml@v2023.01.20
    with:
      lint-directories: 'src'
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Cache Deps
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Run tests
      run: make test
