name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  lint:
    uses: yetanalytics/workflow-linter/.github/workflows/linter.yml@v2024.08.01
    with:
      lint-directories: 'src'
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CI Environment
      uses: yetanalytics/action-setup-env@v2

    - name: Install Chromium
      uses: browser-actions/setup-chrome@v1

    - name: Cache Deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Run tests
      run: make test
